name: Java with Nexus Repository and Telegram Notification

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload to Nexus
      run: |
        FILE_PATH="/test"  # Укажите путь к вашему файлу
        FILE_NAME="testfile.txt" # Укажите имя файла
        curl -u ${{ secrets.username }}:${{ secrets.password }} -T "$FILE_NAME" "https://nexus.2units.ru:8082/repository/docs/$FILE_PATH"
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        
    - name: Send Telegram Notification
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -H "Content-Type: application/json" \
        -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "Загрузил новый файл на Nexus: $FILE_NAME"}'
